### ISSUE TITLE
build a plugin to provide a out-of-box experience

### ISSUE THREAD

**Issue by RocketMaDev** [devgianlu/GhidraProtobufCpp#1]
I would like to try your plugin out, could you please build a portion and put it in Releases?

**Comment by devgianlu** [comment]
I have just compiled this: [ghidra_11.0.1_PUBLIC_20240522_proj.zip](https://github.com/devgianlu/GhidraProtobufCpp/files/15406927/ghidra_11.0.1_PUBLIC_20240522_proj.zip)

But you should probably compile it yourself, you could run this from the project root:

```bash
docker run -it --rm -v .:/proj -v /path/to/ghidra:/ghidra -e GHIDRA_INSTALL_DIR=/ghidra gradle sh -c "cd /proj && gradle"
```

**Comment by RocketMaDev** [comment]
Eh, how to use the plugin? It seems that you don't write about its usage. The plugin is loaded in Ghidra now, but I don't know how to invoke it.

**Comment by devgianlu** [comment]
You can run it from the Script Manager.

**Comment by RocketMaDev** [comment]
Oh no, what can cause it?

```
Cannot invoke "ghidra.program.model.mem.MemoryBlock.getAddressRange()" because the return value of "ghidra.program.model.mem.Memory.getBlock(String)" is null
java.lang.NullPointerException: Cannot invoke "ghidra.program.model.mem.MemoryBlock.getAddressRange()" because the return value of "ghidra.program.model.mem.Memory.getBlock(String)" is null
	at xyz.gianlu.protobuf.MemoryUtil.<init>(MemoryUtil.java:31)
	at xyz.gianlu.protobuf.MemoryUtil.forProgram(MemoryUtil.java:42)
	at FindProtobufDescriptorTables.run(FindProtobufDescriptorTables.java:136)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:403)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:258)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:236)
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:47)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

---------------------------------------------------
Build Date: 2024-Apr-10 1518 EDT
Ghidra Version: 11.0.3
Java Home: /usr/lib/jvm/java-17-graalvm
JVM Version: GraalVM Community 17.0.8
OS: Linux 6.9.0-arch1-1.2-g14 amd64
```

**Comment by devgianlu** [comment]
Looks like your binary does not have the `protodesc_cold` section, the code heavily relies on it so this might not work for you without modifications.

**Comment by RocketMaDev** [comment]
That's a pity. The target elf is stripped. :(

**Comment by RocketMaDev** [comment]
Anyway, the plugin should work.
